[project]
name = "maimai-story-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "httpx>=0.28.1",
    "openai>=2.16.0",
    "pillow>=12.1.1",
    "tqdm>=4.67.1",
]
